### ISSUE TITLE
Hardware issue when trying to control an rgb led with the tlc59711

### ISSUE THREAD

**Issue by plankatron** [circusautomatic/cthuloid#5]
From various tests I believe there is a problem in how the light board pcb is designed.
It initially came up when controlling a single 100w led at 10khz with a 16 bit pwm resolution. We found that the useable values were constrained by about half, this is to say that visually the top or low end values would yield no real visual difference in light intensity. We fixed this in a way by running at 1khz  and a 470uf cap on the output for  smoothing which resulted in a much broader range of useable values.

Now we are using the tlc59711 led driver to generate a high frequency and high bit signal and the output is severely restricted, initial thoughts of the hardware problem being the Arduino start to seem false and that the real culprit is the lightboard design. Thus this issue is being started to try to figure out the problem and to design a solution.

**Comment by plankatron** [comment]
# Basic test
* Make sure you are running the latest Arduino ide (older versions could work but have not been tested) and have loaded this library for the tlc59711 https://github.com/ulrichstern/Tlc59711/
* Have a 100w led being controlled by an Arduino uno or mega that is using the tlc59711 as a driver
*  Load the helloworld example sketch but make sure in void loop that it is just setting a single value like 
**  tlc.setRGB(65535, 65535,65535);
**  tlc.write();
* Keep changing values to see that the only really useful pwm values are in a tiny range.

Now the real work of figuring out what is causing this and how to get a much larger range from this signal.

**Comment by plankatron** [comment]
Tlc59711 info and data sheets : http://www.ti.com/product/TLC59711
Adafruit product page : https://www.adafruit.com/product/1455
Wiring to Arduino : https://learn.adafruit.com/tlc5947-tlc59711-pwm-led-driver-breakout/connecting-to-the-arduino

**Comment by flintiii** [comment]
So would it be useful to eliminate the Arduino?

**Comment by plankatron** [comment]
![modular-led-mosfet11_schem](https://user-images.githubusercontent.com/5592454/32135546-550353e4-bc01-11e7-9659-ebb05ca2b130.png)
Also a link to the parts list :
http://organize.7rnx.net/projects/sad-robot-workspace/wiki/PCB#Parts-List

**Comment by plankatron** [comment]
Thinking that this could work as a simplified circuit design but it still needs to invert the signal somehow?

![rfp30n06le-arduino-lightbulb](https://user-images.githubusercontent.com/5592454/32135620-27b79890-bc02-11e7-95d8-dacf7672781a.png)

**Comment by flintiii** [comment]
These pictures are excellent!

**Comment by flintiii** [comment]
I am wondering if you can accomplish the inversion you need in software...

**Comment by plankatron** [comment]
info for dimming led's with the esp32 
https://techtutorialsx.com/2017/06/15/esp32-arduino-led-pwm-fading/
